config/routes.rb
Rails.application.routes.draw do
  
  resources :tags
  root :to => "members#index"

  resources :members, only: %i[index show] do
    resource :notes, controller: 'members/notes', only: %i[new create]
    resource :contents, controller: 'members/contents', only: %i[new create edit update]
  end

  resources :activities, only: %i[index]
end

app/models/activity.rb
class Activity < ApplicationRecord
  belongs_to :member
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/content.rb
class Content < ApplicationRecord
  belongs_to :member

  validates :url, presence: true
end

app/models/member.rb
class Member < ApplicationRecord
    has_many :activities
    has_many :notes
    has_many :contents
    has_and_belongs_to_many :tags, join_table: :members_tags
end

app/models/note.rb
class Note < ApplicationRecord
  belongs_to :member

  validates :body, presence: true
end

app/models/tag.rb
class Tag < ApplicationRecord
    has_and_belongs_to_many :members, join_table: :members_tags
end

app/controllers/activities_controller.rb
class ActivitiesController < ApplicationController
  def index
    @activities = Activity.all
  end
end

app/controllers/application_controller.rb
require "application_responder"

class ApplicationController < ActionController::Base
  self.responder = ApplicationResponder
  respond_to :html

end

app/controllers/members/contents_controller.rb
module Members
    class ContentsController < ApplicationController
    
        respond_to :js, only: %i[new create edit update]

        def new
            @member = Member.find(params[:member_id])
            @content = @member.contents.new
            respond_with @member, @content
        end

        def create
            @member = Member.find(params[:member_id])
            @content = @member.contents.new(content_params)

            if @content.save
                redirect_to @member
            else
                render :new
            end
        end

        # def edit
        #     @member = Member.find(params[:member_id])
        #     @content = @content.find(params[:content_id])
        #     respond_with @member, @content
        # end

        # def update
        #     @member = Member.find(params[:member_id])
        #     @content = @content.find(params[:content_id])

        #     if @content.update(content_params)
        #         redirect_to @member
        #     else
        #         render :edit
        #     end
        # end


        private

        def content_params
            params.require(:content).permit(:description, :url, :type_of_content)
        end
    end
end

app/controllers/members/notes_controller.rb
module Members
  class NotesController < ApplicationController

    respond_to :js, only: %i[new create]

    def new
      @member = Member.find(params[:member_id])
      @note = @member.notes.new
      respond_with @member, @note
    end

    def create
      @member = Member.find(params[:member_id])
      @note = @member.notes.new(note_params)

      if @note.save
        redirect_to @member
      else
        render :new
      end
    end


    private

    def note_params
      params.require(:note).permit(:body)
    end
  end
end

app/controllers/members_controller.rb
class MembersController < ApplicationController
  def index
    @members = MemberService.sort_by_most_activities_count()
  end

  def show
    @member = Member.find(params[:id])
  end
end

app/controllers/tags_controller.rb
class TagsController < ApplicationController
end

app/helpers/activities_helper.rb
module ActivitiesHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/contents_helper.rb
module ContentsHelper
end

app/helpers/members_helper.rb
module MembersHelper
end

app/helpers/notes_helper.rb
module NotesHelper
end

app/helpers/tags_helper.rb
module TagsHelper
end

app/views/activities/index.html.erb
<h1>Activity feed</h1>
<p>All activities:</p>
<div class="list-group">
  <% @activities.each do |activity| %>
    <div class="list-group-item list-group-item-action mb-4" target='_blank' rel='noopener'>
      <h5 class="mb-1">
        <%= link_to activity.member.email, member_path(activity.member) %>
        did <%= activity.action %>
      </h5>
      <p class="mb-1 ps-2 border-start border-3 text-secondary"><%= activity.description %></p>
      <%= link_to activity.url, target: "_blank", rel: "noopener" do %>
        <small class="text-primary"><%= activity.url %></small>
      <% end %>
    </div>
  <% end %>
</div>

app/views/layouts/_navigation.html.erb
<nav class="navbar navbar-expand-lg navbar-light bg-light">
  <div class="container-fluid">
    <%= link_to "Mini Orbit", root_path, class: 'navbar-brand' %>
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav me-auto mb-2 mb-lg-0">
        <li class="nav-item">
          <%= link_to 'Members', members_path, class: 'nav-link' %>
        </li>
        <li class="nav-item">
          <%= link_to 'Activities', activities_path, class: 'nav-link' %>
        </li>
      </ul>
    </div>
  </div>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Mini Orbit</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <header>
      <%= render 'layouts/navigation' %>
    </header>
    <div class="container-xxl my-md-4 bd-layout">
      <main role="main">
        <%= content_for?(:content) ? yield(:content) : yield %>
      </main>
    </div>
  </body>
</html>

app/views/members/contents/_form.html.erb
<%= form_for @content, url: member_contents_path(@content.member), remote: true do |form| %>
  <div class="modal-header">
    <h5 class="modal-title">Add a content</h5>
    <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
  </div>
  <div class="modal-body">
    <div>
      <%= form.label :url, class: 'form-label' %><br>
      <%= form.text_field :url, class: 'form-control' %>
      <% @content.errors.full_messages_for(:url).each do |message| %>
        <div><%= message %></div>
      <% end %>
    </div>
    <div>
      <%= form.label :type_of_content, class: 'form-label' %><br>
      <%= form.select :type_of_content, [['Blog Post', 'Blog Post'], ['Youtube Video', 'Youtube Video']], {}, {class: 'form-control'} %>
    </div>
    <div>
      <%= form.label :description, class: 'form-label' %><br>
      <%= form.text_field :description, class: 'form-control' %>
      <% @content.errors.full_messages_for(:description).each do |message| %>
        <div><%= message %></div>
      <% end %>
    </div>
  </div>
  <div class="modal-footer">
    <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">Close</button>
    <%= form.submit 'Save', class: 'btn btn-primary' %>
  </div>
<% end %>

app/views/members/contents/edit.js.erb
$('#contentModal').find(".modal-content").html("<%= j (render 'form') %>")
var myContentModal = new bootstrap.Modal(document.getElementById('contentModal'))
myContentModal.show()

app/views/members/contents/new.js.erb
$('#contentModal').find(".modal-content").html("<%= j (render 'form') %>")
var myContentModal = new bootstrap.Modal(document.getElementById('contentModal'))
myContentModal.show()

app/views/members/index.html.erb
<h1>Our Members</h1>
<table class="table">
  <thead>
    <tr>
      <th scope="col">Email</th>
      <th scope="col">Name</th>
      <th scope="col">GitHub</th>
      <th scope="col">Twitter</th>
      <th scope="col">Location</th>
    </tr>
  </thead>
  <tbody>
    <% @members.each do |member| %>
      <tr>
        <th scope="row"><%= link_to member.email, member_path(member) %></th>
        <td><%= member.name %></td>
        <td><%= member.github %></td>
        <td><%= member.twitter %></td>
        <td><%= member.location %></td>
      </tr>
    <% end %>
  </tbody>
</table>

app/views/members/notes/_new.html.erb
<%= form_for @note, url: member_notes_path(@note.member), remote: true do |form| %>
  <div class="modal-header">
    <h5 class="modal-title">Add a note</h5>
    <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
  </div>
  <div class="modal-body">
    <div>
      <%= form.label :body, class: 'form-label' %><br>
      <%= form.text_field :body, class: 'form-control' %>
      <% @note.errors.full_messages_for(:body).each do |message| %>
        <div><%= message %></div>
      <% end %>
    </div>
  </div>
  <div class="modal-footer">
    <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">Close</button>
    <%= form.submit 'Save', class: 'btn btn-primary' %>
  </div>
<% end %>

app/views/members/notes/new.js.erb
$('#noteModal').find(".modal-content").html("<%= j (render 'new') %>")
var myModal = new bootstrap.Modal(document.getElementById('noteModal'))
myModal.show()

app/views/members/show.html.erb
<h1><%= @member.email %>’s profile</h1>
<div class="d-flex">
  <div class="w-25">
    <h2>About</h2>
    <div class="card" style="width: 18rem;">
      <ul class="list-group list-group-flush">
        <% if @member.name.present? %>
          <li class="list-group-item">Name: <%= @member.name %></li>
        <% end %>
        <% if @member.email.present? %>
          <li class="list-group-item">Email: <%= @member.email %></li>
        <% end %>
        <% if @member.github.present? %>
          <li class="list-group-item">GitHub: <%= @member.github %></li>
        <% end %>
        <% if @member.twitter.present? %>
          <li class="list-group-item">Twitter: <%= @member.twitter %></li>
        <% end %>
        <% if @member.location.present? %>
          <li class="list-group-item">Location: <%= @member.location %></li>
        <% end %>
        <% if @member.tags.present? %>
          <li class="list-group-item">Tags: <%= @member.tags.pluck(:name).join(', ') %></li>
        <% end %>
      </ul>
      <div class="card-body">
        <%= link_to 'Add a note', new_member_notes_path(@member),  {:remote => true, 'data-toggle' =>  "modal", 'data-target' => '#noteModal', class: 'text-primary'}  %>
      </div>
      <div class="card-body">
        <%= link_to 'Add a content', new_member_contents_path(@member),  {:remote => true, 'data-toggle' =>  "modal", 'data-target' => '#contentModal', class: 'text-primary'}  %>
      </div>
    </div>
  </div>
  <div>
    <h2>Their content</h2>
    <% @member.contents.each do |content| %>
      <figure>
        <blockquote class="blockquote type_of_content">
          <p><%= content.type_of_content %></p>
        </blockquote>
        <blockquote class="blockquote description">
          <p><%= content.description %></p>
        </blockquote>
        <blockquote class="blockquote url">
          <p><%= content.url %></p>
        </blockquote>
        <figcaption class="blockquote-footer">
          <%= content.created_at %>
        </figcaption>
        <div>
          <%# <%= link_to 'Edit the content', edit_member_contents_path(content),  {:remote => true, 'data-toggle' =>  "modal", 'data-target' => '#contentModal', class: 'text-secondary'} %>
        </div>
      </figure>
    <% end %>
    <br/>
    <h2>Their notes</h2>
    <% @member.notes.each do |note| %>
      <figure>
        <blockquote class="blockquote">
          <p><%= note.body %></p>
        </blockquote>
        <figcaption class="blockquote-footer">
          <%= note.created_at %>
        </figcaption>
      </figure>
    <% end %>
    <br/>
    <h2>Their activities</h2>
    <div class="list-group">
      <% @member.activities.each do |activity| %>
        <%= link_to activity.url, class: "list-group-item list-group-item-action mb-4", target: '_blank', rel: 'noopener' do %>
          <h5 class="mb-1"><%= activity.action %></h5>
          <p class="mb-1 ps-2 border-start border-3 text-secondary"><%= activity.description %></p>
          <small class="text-primary"><%= activity.url %></small>
        <% end %>
      <% end %>
    </div>
  </div>
</div>

<div id="noteModal" class="modal" tabindex="-1">
  <div class="modal-dialog">
    <div class="modal-content">
      
    </div>
  </div>
</div>

<div id="contentModal" class="modal" tabindex="-1">
  <div class="modal-dialog">
    <div class="modal-content">
      
    </div>
  </div>
</div>